### ISSUE TITLE
git-ftp

### ISSUE THREAD

**Issue by ana-balica** [TUM-FAF/FAFSite#19]
Set up a hook to send all the diffs from master branch to the ftp where the website lives.

**Comment by ana-balica** [comment]
Found http://www.deployhq.com/
It is simple and ease to use. The service is free for a single repo with less than 10 deploys per day, which is perfect for our purposes.
At the moment there is a problem with credentials. Most probably some of the settings aren't accurate (active vs passive ftp maybe). 
Will set up the deployment asap.

**Comment by ana-balica** [comment]
Lol. Managed to deploy it, but since we don't have a normal way to handle production and development environment, the deploy from master branch has overwritten the `setting.py`. 
Therefore this issue will be done when issue #13 will be solved :)

**Comment by mishunika** [comment]
Add `settings.py` to `.gitignore` and create for reference something like `default.settings.py`.
Upload the needed settings to the production server and forget about it ;)

**Comment by ana-balica** [comment]
What exactly do you mean by `default.settings.py`? 
For production this is perfect. But for staging most of guys will need `settings.py` to work out of the box.
Anyway be more explicit :)

**Comment by mishunika** [comment]
I meant that you can create a `default.settings.py` with default settings, such that any of the devs can copy it to `setting.py` and change it in order to fit their needs. I think that it's not okay to publish all email and database credentials here. IMO ;)

Also, `default.settings.py` needs to be updated if some new apps will be created/installed.

**Comment by ana-balica** [comment]
Yeah. I also was thinking about credentials. At the moment one can do lots of mining on github. 
So I'll do it your way.
Thanks Mike.

**Comment by mishunika** [comment]
Oh, btw. You can create a file like `credentials.py` and define there vars for db user, db pass etc and import them in `settings.py`... Dunno how this fits into django's standards, but it seems to be quite comfortable... ;)

**Comment by ana-balica** [comment]
Ta-dam. Works nice :)
Here is your deploy account.
https://ananas.deployhq.com

Free account grants us a single user, single deployment server and 10 deploys per day. More than enough.
