### ISSUE TITLE
Main page URL consistency

### ISSUE THREAD

**Issue by ralienpp** [TUM-FAF/FAFSite#3]
The landing page is / by default, but if you click the logo on top it is /index. From a search bot's perspective you have two identical pages - which is not good. Ideally, it should always be / because it is shorter. Regardless of what you choose to do, the URLs should be consistent.

**Comment by ana-balica** [comment]
The issue is fixed and in production.
Also in the footer FAF URL had the same inconsistency.
Thx Alex.
