### ISSUE TITLE
On courses page, one course throws to an invalid URL

### ISSUE THREAD

**Issue by vledniov** [TUM-FAF/FAFSite#34]
http://i.imgur.com/piXjmoT.png

The URL is invalid, and throws a 404 on clicking on it.

**Comment by ana-balica** [comment]
thx Vlad

as soon as i can access the page (there is some crazy latency and i can't login to admin panel), i will fix that stuff.
i know the reason why, but forgot to do it :cactus:

**Comment by ana-balica** [comment]
http://faf.utm.md/courses/information-system-design/
